import { Loading } from 'sharedComponents'
import { gql } from '@apollo/client'
import { useMutation } from '@apollo/client/react'
import { Box, Button, Card, css, IconButton, Link, Typography } from '@mui/material'
import Pause from '@mui/icons-material/Pause'
import PlayArrow from '@mui/icons-material/PlayArrow'
import Avatar from '@mui/material/Avatar'
import ListItem from '@mui/material/ListItem'
import ListItemAvatar from '@mui/material/ListItemAvatar'
import ListItemText from '@mui/material/ListItemText'
import TextField from '@mui/material/TextField'
import { context } from 'context'
import type { TPlaylistEntry } from 'playlist-generator-utilities'
import { useCallback, useContext, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router'
import { ELocalStorageItems, getLocalStorage } from 'utilities'

const ADVERTISEMENT = ' Generated by playlists.sillysideprojects.com'

const playlistLinkCSS = css`
  text-decoration: none;
  margin-right: 0.25rem;
  
  &:hover {
    text-decoration: underline;
  }
`

const SAVE_PLAYLIST_MUTATION = gql`
  mutation savePlaylist($accessToken: String! $playlistTitle: String! $playlistDescription: String! $uris: [String]!) {
    savePlaylist(accessToken: $accessToken, playlistTitle: $playlistTitle, playlistDescription: $playlistDescription, uris: $uris) 
  }
`

const PlaylistItem = ({
  data,
  isPlaying,
  onPlay,
}: { data: TPlaylistEntry; isPlaying: boolean; onPlay: (trackId: string, previewUrl: string) => void }) => {
  const Artists = useMemo(() => {
    return data.artists.map(({ name, href }) => (
      <Link css={playlistLinkCSS} key={href} target="_blank" href={href}>
        {name}
      </Link>
    ))
  }, [data.artists])

  const handlePlayClick = useCallback(() => {
    if (data.previewUrl) {
      onPlay(data.id, data.previewUrl)
    } else {
      window.open(data.href, '_blank', 'noopener,noreferrer')
    }
  }, [data.previewUrl, data.id, data.href, onPlay])

  return (
    <ListItem>
      <ListItemAvatar>
        <Link target="_blank" href={data.album.href}>
          <Avatar variant="square" alt={data.name} src={data.image} />
        </Link>
      </ListItemAvatar>
      <ListItemText
        primary={
          <Link css={playlistLinkCSS} target="_blank" href={data.href}>
            {data.name}
          </Link>
        }
        secondary={Artists}
      />
      <IconButton edge="end" aria-label={data.previewUrl ? 'preview track' : 'play on spotify'} onClick={handlePlayClick}>
        {isPlaying ? <Pause /> : <PlayArrow />}
      </IconButton>
    </ListItem>
  )
}

interface PlaylistParams {
  playlistEntries: TPlaylistEntry[]
  initialTitle: string
  initialDescription: string
  resetStateCallback: () => void
}
const Playlist = ({ playlistEntries, initialTitle, initialDescription, resetStateCallback }: PlaylistParams) => {
  const [savePlaylist] = useMutation<{ savePlaylist: string }>(SAVE_PLAYLIST_MUTATION)
  const [playlistTitle, setPlaylistTitle] = useState(initialTitle)
  const [playlistDescription, setPlaylistDescription] = useState(initialDescription + ADVERTISEMENT)
  const [isSavingPlaylist, setIsSavingPlaylist] = useState(false)
  const [playingTrackId, setPlayingTrackId] = useState<string | null>(null)
  const audioRef = useRef<HTMLAudioElement>(null)
  const navigate = useNavigate()
  const { dispatch } = useContext(context)

  const handlePlay = useCallback((trackId: string, previewUrl: string) => {
    const audio = audioRef.current
    if (!audio) return

    if (playingTrackId === trackId) {
      audio.pause()
      setPlayingTrackId(null)
      return
    }

    audio.src = previewUrl
    audio.play()
    setPlayingTrackId(trackId)
  }, [playingTrackId])

  const handleAudioEnded = useCallback(() => {
    setPlayingTrackId(null)
  }, [])

  const handleSavePlaylistSubmit = useCallback(async () => {
    setIsSavingPlaylist(true)
    const uris = playlistEntries.map(({ uri }) => uri)

    const accessToken = getLocalStorage(ELocalStorageItems.AccessToken)
    if (!accessToken) {
      dispatch({ type: 'ADD_ALERT', data: { text: 'You need to login first', severity: 'info' } })
      navigate('/')
      return
    }
    const response = await savePlaylist({ variables: { uris, playlistTitle, playlistDescription, accessToken } })
    if (response.data) {
      dispatch({
        type: 'ADD_ALERT',
        data: { text: 'Playlist created!', url: response.data.savePlaylist, severity: 'success' },
      })
      resetStateCallback()
    } else {
      dispatch({ type: 'ADD_ALERT', data: { text: 'Failed to save playlist', severity: 'error' } })
    }

    setIsSavingPlaylist(false)
  }, [playlistEntries, playlistTitle, savePlaylist, navigate, dispatch, playlistDescription, resetStateCallback])

  const Playlist = useMemo(() => {
    // Sometimes duplicate tracks come back in a playlist. Currently it doesn't look possible to dedup a playlist and keep its integrity.
    return playlistEntries.map((result, index) => (
      <PlaylistItem
        key={`${result.uri}_${index}`}
        data={result}
        isPlaying={playingTrackId === result.id}
        onPlay={handlePlay}
      />
    ))
  }, [playlistEntries, playingTrackId, handlePlay])

  if (isSavingPlaylist) {
    return <Loading />
  }

  return (
    <Box>
      <audio ref={audioRef} onEnded={handleAudioEnded} />
      <TextField
        fullWidth
        label="Title this Playlist"
        type="title"
        margin="normal"
        value={playlistTitle}
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
          setPlaylistTitle(event.target.value)
        }}
        css={{ marginBottom: '1rem' }}
      />
      <TextField
        fullWidth
        label="Give it a Description"
        type="description"
        margin="normal"
        value={playlistDescription}
        multiline
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
          setPlaylistDescription(event.target.value)
        }}
        css={{ marginBottom: '1rem' }}
      />
      <Typography variant="h6" component="div" gutterBottom>
        Preview Playlist ({playlistEntries.length} Tracks)
      </Typography>
      <Card
        component="ul"
        sx={{
          overflowY: 'scroll',
          maxHeight: '30vh',
          margin: '0.5rem 0',
          border: '1px solid #363636',
          borderRadius: '0.4rem',
        }}
      >
        {Playlist}
      </Card>
      <Button fullWidth variant="contained" disabled={isSavingPlaylist} onClick={handleSavePlaylistSubmit}>
        Save it to your Spotify
      </Button>
      <Button fullWidth variant="text" onClick={resetStateCallback}>
        Start Over
      </Button>
    </Box>
  )
}

export default Playlist
